searchguard:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
    authc:
      my-auth:
        enabled: true
        http_enabled: true
        transport_enabled: false
        order: 5
        http_authenticator:
          type: "basic"
          challenge: false
        authentication_backend:
          type: "com.example.es.sg.auth.MyAuthenticationBackend"
          config: